print("enter a week day number : ")
a = parse(Int, readline())
if (a==1)
    println("Monday")
elseif (a==2)
    println("Tuesday")
elseif (a==3)
    println("Wednesday")
elseif (a==4)
    println("Thursday")
elseif (a==5)
    println("Friday")
elseif (a==6)
    println("Saturday")
elseif (a==7)
    println("Sunday")
else
    println("Invalid weekday!")
end